[FEAT] Support rotate left and right operations
FhenixProtocol/fheos pull request #141
Opened 2024-09-11 07:29 UTC by roeezolantz

2024-09-11 09:03 UTC, roeezolantz commented on solgen/common.ts
> +const patternAllowedOperationsEbool = ["ne|eq|^and$|^or$|xor|sealoutput|select|seal|decrypt|not"];
Fix for conflict with `ror`

2024-09-12 10:17 UTC, liorbond commented
LGTM, generally I'm missing some unittests in Engine, Driver, etc. please make sure to follow the other operations and see what are the tests that are written for them

2024-09-12 10:18 UTC, liorbond requested changes

2024-09-12 10:18 UTC, liorbond commented on precompiles/contracts.go
> +func Rol(utype byte, lhsHash []byte, rhsHash []byte, tp *TxParams) ([]byte, uint64, error) {
Rol and Ror functions are and always will be the same, therefore I would probably create a helper function somewhere for "rotate" that does everything for which the only differences (based on function input or something?) are the "functionName" and the direction (for which you can choose calling ror or rol)

2024-09-12 10:18 UTC, liorbond commented on solidity/tests/contracts/Rol.sol
> +    function rol(string calldata test, uint256 a, uint256 b) public pure returns (uint256 output) {
Did you write tests to trigger and test those functions?

2024-09-15 10:56 UTC, roeezolantz commented on precompiles/contracts.go
> +func Rol(utype byte, lhsHash []byte, rhsHash []byte, tp *TxParams) ([]byte, uint64, error) {
I've noticed that it might corrupt the solgen generator due to the way the`contracts_parser.ts` works, cuz it's relying on function calls like `get2VerifiedOperands` to understand that it's 2 operands, and having `if lhs.UintType != rhs.UintType` to make sure they are the same types and etc..
BUT, i'll add support and lmk if you think it's better

2024-09-16 09:36 UTC, roeezolantz commented on precompiles/gas.go
> +	case types.Shl, types.Shr, types.Rol, types.Ror:
TEMP

2024-09-16 12:35 UTC, eshelB approved these changes
Nice!

2024-09-16 12:35 UTC, eshelB commented on solgen/contracts_parser.ts
> +      const match = trimmedLine.match(solgenVerifiedOperands);
maybe put this block together with the other `solgen: ` matches above? it's kinda separate. Also why does it require a separate push to the `specificFunctionAnalysis` that is not required for other solgen comments? I may have missed something

2024-09-17 12:31 UTC, toml01 commented on solidity/tests/precompiles.test.ts
> +  };
If I'm not mistaken, these test cases check only rotates of zeroes - can we also test rotates of a turned on bit?

2024-09-17 13:25 UTC, roeezolantz commented on solidity/tests/precompiles.test.ts
> +  };
:busted:

2024-09-17 13:35 UTC, roeezolantz commented on precompiles/contracts.go
> +func Rol(utype byte, lhsHash []byte, rhsHash []byte, tp *TxParams) ([]byte, uint64, error) {
Following the conversations with Tom and Itzik, i'm reverting this refactor for now as it's out of scope here and can be handled better as a standalone separated task

2024-09-17 13:39 UTC, toml01 approved these changes

2024-09-18 08:41 UTC, roeezolantz commented on precompiles/gas.go
> +	case types.Shl, types.Shr, types.Rol, types.Ror:
Benchmark on 10 runs each - 
(running bench of 100 each now as well)
<img width="877" alt="image" src="https://github.com/user-attachments/assets/8d492ec6-ccb8-4ccb-aeaf-770a1e425f44">

2024-09-19 09:56 UTC, roeezolantz commented on precompiles/gas.go
> +	case types.Shl, types.Shr, types.Rol, types.Ror:
After 100 runs each : 
![image](https://github.com/user-attachments/assets/345e0e2d-94f2-4c58-8cd7-be3215878a5b)

2024-09-19 10:29 UTC, liorbond approved these changes

2024-09-19 14:32 UTC, merged