Expose /GetNetworkPublicKey
FhenixProtocol/fheos pull request #189
Opened 2024-12-16 15:19 UTC by haimbj1

2024-12-17 09:53 UTC, eshelB approved these changes

2024-12-17 09:53 UTC, eshelB commented on http/main.go
> +	fmt.Printf("Got a getNetworkPublicKey request from %s\n", r.RemoteAddr)
we should probably add a logger instead of printing to stdout if there isn't one already

2024-12-18 09:30 UTC, liorbond commented on http/main.go
> +	fmt.Printf("Got a getNetworkPublicKey request from %s\n", r.RemoteAddr)
Agree, although it might be something that is irrelevant to this scope, we will probably need to do it in a different ticket

2024-12-18 09:33 UTC, liorbond requested changes

2024-12-18 09:33 UTC, liorbond commented on http/main.go
> +		return
```suggestion
		fmt.Println(err.ErrString()) // don't remember the right syntax here
		http.Error(w, err, http.StatusInternalServerError)
		return
```

Err already contains the same string

2024-12-18 09:53 UTC, haimbj1 commented on http/main.go
> +		return
In this specific case the internal error has the same string, so agree,

2024-12-18 10:56 UTC, liorbond approved these changes

2024-12-18 10:57 UTC, merged