runCopro.sh with fhenix as DA
FhenixProtocol/fheos pull request #190
Opened 2024-12-17 13:28 UTC by eshelB

runcopro now deploys a second fhenix chain to act as the DA, and deploys the ct-registry contract to that chain

2024-12-18 09:15 UTC, haimbj1 requested changes

2024-12-18 09:15 UTC, haimbj1 commented on http/runCopro.sh
> +if [ ! -d "$FheosDir" ]; then
Did you mean $CtRegistryDir
Should we enforce the script? or only in certain config?

2024-12-18 09:15 UTC, haimbj1 commented on http/runCopro.sh
> +function runningLocalFhenixSecondInstance {
I suggest edit the runningLocalFhenix  with parameters rather copy the functionality, if you pass name, port1, port2,port3  you can just call this twice with different inputs.

2024-12-18 09:15 UTC, haimbj1 commented on http/runCopro.sh
> +function deployContractCtRegistry {
Same here, we can create a deployContract function that get directory and name, and then you can call it twice under `deployContracts` with TM / CtRegistry

2024-12-18 09:15 UTC, haimbj1 commented on http/runCopro.sh
> +function copyDeployedCtRegistry {
Same here

2024-12-20 11:26 UTC, eshelB commented
do not merge yet, still testing

2024-12-21 17:41 UTC, eshelB commented
merge is possible now

2024-12-22 08:27 UTC, haimbj1 approved these changes

2024-12-22 08:27 UTC, haimbj1 commented on http/runCopro.sh
>      pnpm pnpm clean
Not in your code, but is it intentional pnpm twice?

2024-12-22 09:30 UTC, eshelB commented on http/runCopro.sh
>      pnpm pnpm clean
probably not

2024-12-22 09:31 UTC, eshelB commented
Actually I still find bugs, testing again

2024-12-22 11:59 UTC, merged